"""
MediAegis AI - FastAPI entrypoint
Exposes the Agent Orchestrator over HTTP for the chat frontend.
"""
from fastapi import FastAPI, HTTPException, UploadFile, File, Form
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse, StreamingResponse
from pydantic import BaseModel
import os
import json

from config import settings
from infrastructure.db import init_db
from infrastructure.logger import system_logger, error_logger
from mcp import document_store_server
import orchestrator

init_db()
document_store_server.init_document_store()

app = FastAPI(title="MediAegis AI", description="Agentic AI with MCP Architecture", version="1.0.0")

origins = ["*"] if settings.CORS_ORIGINS == "*" else settings.CORS_ORIGINS.split(",")
app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class ChatRequest(BaseModel):
    query: str
    session_id: str | None = None


class ChatResponse(BaseModel):
    session_id: str
    answer: str
    sources: list
    confidence: float
    evaluation: dict
    disclaimers: list
    risk_level: str
    from_cache: bool | None = False


@app.get("/api/health")
def health():
    return {"status": "ok", "model": settings.OLLAMA_MODEL}


@app.post("/api/chat", response_model=ChatResponse)
def chat(req: ChatRequest):
    if not req.query or not req.query.strip():
        raise HTTPException(status_code=400, detail="Query must not be empty.")
    try:
        result = orchestrator.handle_query(req.query.strip(), req.session_id)
        return result
    except Exception as e:  # noqa: BLE001
        error_logger.error(f"chat endpoint failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/api/tools")
def list_tools():
    from mcp.mcp_client import mcp_client
    return mcp_client.list_tools()


@app.post("/api/chat/stream")
def chat_stream(req: ChatRequest):
    """
    Server-Sent Events endpoint. Streams the Answer Agent's tokens live as
    they're generated by Ollama, preceded by a 'meta' event (sources,
    confidence, risk level) and followed by a 'final' event with full
    evaluation metrics — so the frontend can render incrementally and then
    reconcile with the authoritative final payload.
    """
    if not req.query or not req.query.strip():
        raise HTTPException(status_code=400, detail="Query must not be empty.")

    def event_generator():
        try:
            for event in orchestrator.handle_query_stream(req.query.strip(), req.session_id):
                yield f"event: {event['type']}\ndata: {json.dumps(event['data'])}\n\n"
        except Exception as e:  # noqa: BLE001
            error_logger.error(f"chat_stream failed: {e}")
            yield f"event: error\ndata: {json.dumps({'detail': str(e)})}\n\n"

    return StreamingResponse(event_generator(), media_type="text/event-stream")


# ---------------- RAG document management (institution guidelines / protocols) ----------------

def _extract_text(filename: str, raw: bytes) -> str:
    lower = filename.lower()
    if lower.endswith((".txt", ".md")):
        return raw.decode("utf-8", errors="ignore")
    if lower.endswith(".pdf"):
        try:
            from pypdf import PdfReader
            import io
            reader = PdfReader(io.BytesIO(raw))
            return "\n".join(page.extract_text() or "" for page in reader.pages)
        except ImportError:
            raise HTTPException(
                status_code=400,
                detail="PDF support requires the 'pypdf' package. Run: pip install pypdf",
            )
    raise HTTPException(status_code=400, detail="Unsupported file type. Use .txt, .md, or .pdf")


@app.post("/api/documents")
async def upload_document(file: UploadFile = File(...), title: str | None = Form(None)):
    raw = await file.read()
    text = _extract_text(file.filename, raw)
    if not text.strip():
        raise HTTPException(status_code=400, detail="No extractable text found in the uploaded file.")
    result = document_store_server.ingest_document(title or file.filename, text)
    return result


@app.get("/api/documents")
def get_documents():
    return document_store_server.list_documents()


@app.delete("/api/documents/{document_id}")
def remove_document(document_id: str):
    deleted = document_store_server.delete_document(document_id)
    if not deleted:
        raise HTTPException(status_code=404, detail="Document not found.")
    return {"deleted": True, "document_id": document_id}


# ---------------- Admin analytics dashboard data ----------------

@app.get("/api/admin/stats")
def admin_stats():
    from infrastructure import db as db_module
    return db_module.get_admin_stats()


# ---------------- Serve the frontend (single-origin, no separate server needed) ----------------
FRONTEND_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "frontend")

if os.path.isdir(FRONTEND_DIR):
    app.mount("/assets", StaticFiles(directory=os.path.join(FRONTEND_DIR, "assets")), name="assets")

    @app.get("/")
    def serve_index():
        return FileResponse(os.path.join(FRONTEND_DIR, "index.html"))

    @app.get("/style.css")
    def serve_css():
        return FileResponse(os.path.join(FRONTEND_DIR, "style.css"))

    @app.get("/script.js")
    def serve_js():
        return FileResponse(os.path.join(FRONTEND_DIR, "script.js"))

    @app.get("/admin.html")
    def serve_admin():
        return FileResponse(os.path.join(FRONTEND_DIR, "admin.html"))

    @app.get("/admin.css")
    def serve_admin_css():
        return FileResponse(os.path.join(FRONTEND_DIR, "admin.css"))

    @app.get("/admin.js")
    def serve_admin_js():
        return FileResponse(os.path.join(FRONTEND_DIR, "admin.js"))


if __name__ == "__main__":
    import uvicorn
    system_logger.info(f"Starting MediAegis AI on {settings.APP_HOST}:{settings.APP_PORT}")
    uvicorn.run("main:app", host=settings.APP_HOST, port=settings.APP_PORT, reload=True)
